- name: update yum
  shell: yum update -y
- name: 移除mysql
  shell: yum -y remove mysql
- name: 安装mysql
  shell: yum install -y mysql && yum install -y mysql-server
- name: 启动mysql服务
  shell: systemctl start mysqld.service
