- name: 安装nginx yum repo
  shell: sudo rpm -Uvh http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
- name: 安装nginx
  shell: sudo yum install -y nginx
- name: 拷贝配文文件
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
- name: 拷贝php测试文件
  template: src=index.php dest=/usr/share/nginx/html/index.php
- name: 开机自启动
  shell: sudo systemctl enable nginx  && sudo systemctl start nginx
- name: 开放80端口
  shell: firewall-cmd --zone=public --add-port=80/tcp --permanent
